// resources/js/Pages/Top.styles.js

// 背景グラデ
export const BG_GRADIENT =
    "radial-gradient(1200px 800px at 20% 10%, rgba(59,130,246,0.04), transparent 60%)," +
    "radial-gradient(900px 700px at 90% 20%, rgba(236,72,153,0.03), transparent 55%)," +
    "radial-gradient(900px 700px at 65% 90%, rgba(16,185,129,0.03), transparent 55%)," +
    "linear-gradient(135deg, #FAFAFA 0%, #F5F5F5 55%, #FAFAFA 100%)";

export const styles = {
    page: {
        minHeight: "100vh",
        background: BG_GRADIENT,
        color: "#333333",
        overflow: "hidden",
    },

    topbar: {
        height: 64,
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "0 18px",
        borderBottom: "1px solid rgba(0,0,0,0.08)",
        background: "rgba(255,255,255,0.95)",
        backdropFilter: "blur(10px)",
    },
    brand: { display: "flex", flexDirection: "column", gap: 2 },
    brandTitle: {
        fontWeight: 900,
        letterSpacing: 0.4,
        fontSize: 18,
        color: "#333",
    },
    brandSub: { fontSize: 12, opacity: 0.6, color: "#666" },

    myBtn: {
        border: "1px solid rgba(0,0,0,0.12)",
        background: "#FFFFFF",
        color: "#333",
        padding: "10px 12px",
        borderRadius: 12,
        cursor: "pointer",
        fontWeight: 900,
        boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
    },

    menuBtn: {
        border: "1px solid rgba(0,0,0,0.12)",
        background: "#FFFFFF",
        color: "#333",
        padding: "10px 12px",
        borderRadius: 12,
        cursor: "pointer",
        fontWeight: 800,
        boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
    },

    main: {
        display: "flex",
        gap: 14,
        height: "calc(100vh - 64px - 64px)",
        padding: 14,
    },

    plaza: {
        position: "relative",
        flex: 1,
        height: "100%",
        borderRadius: 18,
        border: "1px solid rgba(0,0,0,0.08)",
        overflow: "hidden",
        background: "#FFFFFF",
        boxShadow: "0 4px 20px rgba(0,0,0,0.08)",
    },

    bgLayer: {
        position: "absolute",
        inset: 0,
        backgroundImage: `
			url("/images/plaza_bg.jpg"),
			radial-gradient(600px 380px at 20% 30%, rgba(59,130,246,0.05), transparent 60%)
		`,
        backgroundSize: "cover",
        backgroundPosition: "center",
        backgroundRepeat: "no-repeat",
        animation: "floatBG 10s ease-in-out infinite",
        pointerEvents: "none",
    },

    dot: {
        position: "absolute",
        width: 36,
        height: 36,
        transform: "translate(-50%, -50%)",
        borderRadius: 999,
        border: "2px solid rgba(0,0,0,0.15)",
        background: "transparent",
        padding: 0,
        cursor: "pointer",
    },
    dotCore: {
        display: "block",
        width: "100%",
        height: "100%",
        borderRadius: 999,
    },
    dotLabel: {
        position: "absolute",
        left: "50%",
        top: 18,
        transform: "translateX(-50%)",
        padding: "6px 10px",
        borderRadius: 999,
        background: "rgba(255,255,255,0.95)",
        border: "1px solid rgba(0,0,0,0.10)",
        fontSize: 12,
        whiteSpace: "nowrap",
        backdropFilter: "blur(8px)",
        pointerEvents: "none",
        marginTop: 8,
        color: "#333",
        boxShadow: "0 2px 8px rgba(0,0,0,0.08)",
    },

    detailPanel: {
        position: "absolute",
        left: 16,
        right: 16,
        top: 16,
        maxWidth: 720,
        borderRadius: 18,
        border: "1px solid rgba(0,0,0,0.10)",
        background: "rgba(255,255,255,0.98)",
        backdropFilter: "blur(12px)",
        boxShadow: "0 8px 32px rgba(0,0,0,0.12)",
        padding: 14,
    },
    detailHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 10,
        marginBottom: 10,
    },
    detailName: {
        fontWeight: 900,
        fontSize: 16,
        display: "flex",
        alignItems: "center",
        gap: 10,
        color: "#333",
        flexWrap: "wrap",
    },
    detailNow: {
        fontSize: 12,
        opacity: 0.8,
        fontWeight: 800,
        border: "1px solid rgba(0,0,0,0.12)",
        padding: "6px 10px",
        borderRadius: 999,
        background: "#F5F5F5",
        color: "#333",
    },
    meTag: {
        fontSize: 12,
        fontWeight: 900,
        padding: "6px 10px",
        borderRadius: 999,
        background: "rgba(59,130,246,0.10)",
        border: "1px solid rgba(59,130,246,0.25)",
        color: "#1D4ED8",
    },
    closeBtn: {
        width: 34,
        height: 34,
        borderRadius: 12,
        border: "1px solid rgba(0,0,0,0.12)",
        background: "#FFFFFF",
        color: "#333",
        cursor: "pointer",
        fontSize: 18,
        lineHeight: "32px",
    },

    myControls: {
        borderRadius: 14,
        border: "1px solid rgba(0,0,0,0.10)",
        background: "#FFFFFF",
        padding: 12,
        marginBottom: 12,
    },
    myDoingGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
        gap: 8,
        marginTop: 10,
    },
    doingChip: {
        border: "1px solid rgba(0,0,0,0.10)",
        background: "#FFFFFF",
        borderRadius: 12,
        padding: "10px 10px",
        cursor: "pointer",
        textAlign: "left",
    },
    myCommentRow: {
        display: "flex",
        gap: 10,
        marginTop: 10,
        alignItems: "stretch",
    },
    myTextarea: {
        flex: 1,
        resize: "none",
        borderRadius: 12,
        border: "1px solid rgba(0,0,0,0.12)",
        padding: "10px 10px",
        outline: "none",
        fontSize: 13,
        lineHeight: 1.35,
    },
    sendBtn: {
        border: "1px solid rgba(0,0,0,0.12)",
        background: "#111827",
        color: "#FFFFFF",
        padding: "10px 12px",
        borderRadius: 12,
        cursor: "pointer",
        fontWeight: 900,
        boxShadow: "0 1px 3px rgba(0,0,0,0.12)",
        whiteSpace: "nowrap",
    },

    logs: {
        display: "flex",
        flexDirection: "column",
        gap: 12,
        maxHeight: 320,
        overflow: "auto",
        paddingRight: 6,
    },
    logBlock: {
        borderRadius: 14,
        border: "1px solid rgba(0,0,0,0.10)",
        background: "#F9F9F9",
        padding: 12,
    },
    logHeading: {
        display: "flex",
        alignItems: "center",
        fontSize: 14,
        marginBottom: 8,
        color: "#333",
        fontWeight: 600,
    },
    logTime: {
        marginLeft: 8,
        fontSize: 11,
        opacity: 0.6,
        fontWeight: 600,
    },
    msgList: { display: "flex", flexDirection: "column", gap: 8 },
    msgHint: { opacity: 0.5, fontSize: 12, color: "#666" },
    msgRow: { display: "flex" },
    msgBubble: {
        maxWidth: "78%",
        padding: "8px 10px",
        borderRadius: 14,
        border: "1px solid rgba(0,0,0,0.10)",
        fontSize: 13,
        position: "relative",
    },
    otherTag: {
        marginLeft: 8,
        fontSize: 11,
        fontWeight: 800,
        padding: "2px 6px",
        borderRadius: 999,
        background: "rgba(255,255,255,0.25)",
        border: "none",
        cursor: "pointer",
        color: "#fff",
    },
    drawer: {
        width: 300,
        height: "100%",
        borderRadius: 18,
        border: "1px solid rgba(0,0,0,0.10)",
        background: "rgba(255,255,255,0.98)",
        backdropFilter: "blur(14px)",
        boxShadow: "0 8px 32px rgba(0,0,0,0.15)",
        overflow: "hidden",
        flexShrink: 0,
        transform: "translateX(0)",
    },
    drawerHeader: {
        height: 54,
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "0 12px 0 14px",
        borderBottom: "1px solid rgba(0,0,0,0.08)",
    },
    drawerList: {
        padding: 10,
        display: "flex",
        flexDirection: "column",
        gap: 6,
        overflow: "auto",
        height: "100%",
    },
    userRow: {
        display: "flex",
        alignItems: "center",
        gap: 10,
        padding: "10px 10px",
        borderRadius: 14,
        border: "1px solid rgba(0,0,0,0.08)",
        background: "transparent",
        color: "#333",
        cursor: "pointer",
        textAlign: "left",
    },
    userDot: {
        width: 10,
        height: 10,
        borderRadius: 999,
        boxShadow: "0 0 0 4px rgba(0,0,0,0.04)",
    },
    userName: {
        fontWeight: 900,
        fontSize: 13,
        flex: "0 0 auto",
        color: "#333",
    },
    userDoing: {
        fontSize: 12,
        opacity: 0.6,
        marginLeft: "auto",
        color: "#666",
    },

    timeline: {
        height: 64,
        display: "flex",
        alignItems: "center",
        gap: 12,
        padding: "0 14px",
        borderTop: "1px solid rgba(0,0,0,0.08)",
        background: "rgba(255,255,255,0.95)",
        backdropFilter: "blur(10px)",
    },
    timelineLabel: {
        fontWeight: 900,
        fontSize: 12,
        opacity: 0.85,
        padding: "8px 10px",
        borderRadius: 12,
        border: "1px solid rgba(0,0,0,0.12)",
        background: "#FFFFFF",
        flex: "0 0 auto",
        color: "#333",
        boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
    },
    marqueeWrap: {
        position: "relative",
        overflow: "hidden",
        flex: 1,
        height: 40,
        borderRadius: 14,
        border: "1px solid rgba(0,0,0,0.08)",
        background: "#FAFAFA",
    },
    marqueeInner: {
        display: "inline-flex",
        alignItems: "center",
        gap: 18,
        whiteSpace: "nowrap",
        padding: "0 18px",
        height: "100%",
        width: "max-content",
        animation: "marquee 24s linear infinite",
    },
    timelineItem: { fontSize: 13, opacity: 0.75, color: "#333" },

    drawerHeaderRow: {
        width: "100%",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 10,
    },
    drawerBody: {
        height: "calc(100% - 54px)", // header分を引く
        position: "relative",
        overflow: "hidden",
    },

    drawerDetailOverlay: {
        position: "absolute",
        inset: 0,
        padding: 10,
        overflow: "auto",
    },
};
